[package]
name = "pcf2131"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.35", default-features = false }
embedded-hal = "1.0.0"
rtcc = "0.3.1"
